### PR TITLE
DeferredMicroState

### PR DESCRIPTION
**Pull request by taras**
This PR introduced DeferredMicroState class that allows to create values with actions that can return promises. The promises are queued up using `ember-concurrency` with a strategy where last triggered action is always the last value. These microstates can receive promises as initial values. 

DeferredMicroState values are annotated with the following properties:

- isNew: true when value was just recomputed
- isPending: value is being evaluated
- isComplete: after isPending moved from true to false, simultaniously be isError: (true|false)
- error: error that caused to transition to isError: true
- isError: if error occured

# TODO
- [x] Add DeferredMicroState Class
- [x] Add test that last action always wins
- [x] Add test that the value is always available available even when response is decorated
- [x] Add test that state properties (isPending, isComplete, isError) are accessible
- [x] Add test where recompute resets the state after error
- [x] Add test for scenario where async/sync operations are mixed in one MicroState
- [x] Add test for scenario where a promise is passed as initial value

**Warning: there is some strange problem with tests failing in PhantomJS. I'm not sure why they're only failing there.**

### CODE REVIEW

**Comment by cowboyd** [comment]
I'm curious: why not make it just a class that can be extended instead of a mixin?

Also, why not just override `transition`?

**Comment by taras** [comment]
@cowboyd that's a good question. Let me look at that right now.

**Comment by taras** [comment]
@cowboyd `this.transition` does a few core things that are shared by both classes of MicroState. I didn't want to copy and paste the code. I can do that if you think it's better.

**Comment by taras** [comment]
@cowboyd missed part of your question about making a class. We were talking about making it a mixin, that's why I did that. I can make it a class if you prefer.

**Comment by taras** [comment]
I'm rewriting the mechanics. Hopefully will have an updated PR later today.

**Comment by taras** [comment]
@cowboyd I refactored the code to a class and rewrote it from scratch. Previous code didn't make sense, it should be better now.

**Pull request closed without merging**
